Files from the tarball src
mattunlv/ProcessJ-Compiler pull request #22
Opened 2017-10-28 00:25 UTC by mrmdrogers

Hey @mattunlv ,

It looks to me like we may want to go through the changes and make sure they are good before merging this branch in to master.

You can make comments on a line by line basis if you see things you want to keep from master, and I will update the PR.

2017-11-06 21:21 UTC, mattunlv requested changes

2017-11-06 21:21 UTC, mattunlv commented on src/AST/AltStat.java
>  public class AltStat extends Statement {
Keep this version of AltStat as it has the replicated alt features to be used in future developments - note, nothing in the current version uses the replicated alt features.

2017-11-06 21:21 UTC, mattunlv commented on src/AST/ArrayType.java
>  public class ArrayType extends Type {
Keep this version.

2017-11-06 21:21 UTC, mattunlv commented on src/AST/ExternType.java
>      public <S extends Object> S visit(Visitor<S> v) {
keep this version - was added when external types were added.

2017-11-06 21:21 UTC, mattunlv commented on src/AST/NamedType.java
>      public NamedType(Name name, Type type) {
keep this file - this change was probably done when external types were added.

2017-11-06 21:21 UTC, mattunlv commented on src/CodeGeneratorJava/CodeGeneratorJava.java
>  import AST.UnaryPreExpr;
KEEP THIS ONE ;-)

2017-11-06 21:21 UTC, mattunlv commented on src/CodeGeneratorJava/Helper.java
>       * Returns the wrapper class name of primitive data types.
keep this file

2017-11-06 21:21 UTC, mattunlv commented on src/Parser/ProcessJ.cup
> -        | alt_statement
This line must be removed for now!

2017-11-06 21:21 UTC, mattunlv commented on src/ProcessJ/runtime/TimerQueue.java
> -//                System.err.println("[TimerQueue] Unexpected interrupt exception encountered.");
remove //

2017-11-06 21:21 UTC, mattunlv commented on src/Utilities/Log.java
> -    public static boolean doLog = true;
set back to false ;-) and allow to alter ..

2017-11-07 06:24 UTC, mrmdrogers commented
Closing this PR because the tarball was out of date.

The changes are now in https://github.com/mattunlv/ProcessJ/pull/23

2017-11-07 06:24 UTC, closed without merging